# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
    ]
